# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190911_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_actice',
            field=models.BooleanField(default=False, verbose_name='邮箱的有效性'),
        ),
    ]
